name: Build

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build scrcpy
        run: |
          ./patch.sh
          cd termux-packages
          ./scripts/run-docker.sh
          ./scripts/run-docker.sh ./build-package.sh -I scrcpy
          tree
          find . -type f -name '*.deb' -print
